/**
 * Created by Administrator on 2017/6/2.
 */
let baseDomain = 'http://wsz.lanzhangxiu.cn'
let serviceUrl = {
  login: baseDomain + '/api/public/login',
  getBanners: baseDomain + '/api/index/getBanners',
  index: baseDomain + '/api/index/index',
  uploadPhotos: baseDomain + '/api/public/uploadPhotos',
  teamAddOrCancelRelation: baseDomain + '/api/team/addOrCancelRelation',
  teamDetail: baseDomain + '/api/team/teamDetail',
  addSupport: baseDomain + '/api/team/addSupport',
  addTeam: baseDomain + '/api/team/addTeam',
  editeUserInfo: baseDomain + '/api/user/editeUserInfo',
  getProxyByMy: baseDomain + '/api/user/getProxyByMy',
  deleteProxy: baseDomain + '/api/user/deleteProxy',
  kaitongWeishang: baseDomain + '/api/user/kaitongWeishang',
  userDetail: baseDomain + '/api/user/userDetail',
  myProxyLists: baseDomain + '/api/user/myProxyLists',
  getMySubscribeTeams: baseDomain + '/api/user/getMySubscribeTeams',
  weiShangMainPage: baseDomain + '/api/user/weiShangMainPage',
  updateLocation: baseDomain + '/api/user/updateLocation',
  userCenter: baseDomain + '/api/user/userCenter',
  userAddOrCancelRelation: baseDomain + '/api/user/addOrCancelRelation',
  addOrCancelRelation: baseDomain + '/api/team/addOrCancelRelation',
  productLists: baseDomain + '/api/product/productLists',
  releaseGoods: baseDomain + '/api/product/releaseGoods',
  getCategoryLists: baseDomain + '/api/product/getCategoryLists',
  productDetail: baseDomain + '/api/product/productDetail',
  getLeavingMessages: baseDomain + '/api/product/getLeavingMessages',
  releaseLeavingMessage: baseDomain + '/api/product/releaseLeavingMessage',
  addCollection: baseDomain + '/api/product/addCollection',
  deleteCollection: baseDomain + '/api/product/deleteCollection',
  collectionLists: baseDomain + '/api/product/collectionLists',
  fabuProductBySelfLists: baseDomain + '/api/product/fabuProductBySelfLists',
  deleteProduct: baseDomain + '/api/product/deleteProduct',
  editeProduct: baseDomain + '/api/product/editeProduct',
  buyProductByTa: baseDomain + '/api/order/buyProductByTa',
  buyProductBySelf: baseDomain + '/api/order/buyProductBySelf',
  addOrder: baseDomain + '/api/order/addOrder',
  payByOrder: baseDomain + '/api/pay/payByOrder',
  addUserSupport: baseDomain + '/api/user/addUserSupport',
  payByGuarantee: baseDomain + '/api/pay/payByGuarantee',
  confirmDelivery: baseDomain + '/api/order/confirmDelivery',
  updateOrderUserInfo: baseDomain + '/api/order/updateOrderUserInfo',
  confirmByReceipt: baseDomain + '/api/order/confirmByReceipt',
  getMessageLists: baseDomain + '/api/product/getMessageLists',
  weishangMap: baseDomain + '/api/user/weishangMap',
  updateMapUser: baseDomain + '/api/user/updateMapUser',
  extensionErcode: baseDomain + '/api/user/extensionErcode',
  userAccountList: baseDomain + '/api/user/userAccountList',
  getNotReadMessage: baseDomain + '/api/product/getNotReadMessage',
  updateMessageIsRead: baseDomain + '/api/product/updateMessageIsRead',
  deleteReleaseLeavingMessage: baseDomain + '/api/product/deleteReleaseLeavingMessage',
  getShareMoneyLists: baseDomain + '/api/user/getShareMoneyLists'
}
module.exports = serviceUrl
